export const MATCHES = [
  {
    id: 1,
    homeTeam: {
      name: "PSG",
      formation: "4-3-3",
      color: "#21304D",
      flag: "psg.png",
    },
    awayTeam: {
      name: "Manchester City",
      formation: "4-2-3-1",
      color: "#43A1D5",
      flag: "city.png",
    },
    competition: "Ligue des champions",
    season: "2024-25",
    date: "7eme journée de poule",
    score: "4-2",
    players: {
      home: [
        { name: "Donnarumma", position: "G" },
        { name: "Hakimi", position: "DD" },
        { name: "Marquinhos", position: "DCD" },
        { name: "Pacho", position: "DCG" },
        { name: "Nuno Mendes", position: "DG" },
        { name: "Joao Neves", position: "MCG" },
        { name: "Vitinha", position: "MD" },
        { name: "Fabian Ruiz", position: "MCD" },
        { name: "Barcola", position: "ALG" },
        { name: "Doue", position: "AT" },
        { name: "Lee", position: "ALD" },
        { name: "Dembele", position: "SUB0" },
        { name: "Ramos", position: "SUB1" },
        { name: "Zaire-emery", position: "SUB2" },
        { name: "Hernandez", position: "SUB3" },
      ],
      away: [
        { name: "Ederson", position: "G" },
        { name: "Matheus Nunes", position: "DD" },
        { name: "Akanji", position: "DCD" },
        { name: "Ruben Dias", position: "DCG" },
        { name: "Gvardiol", position: "DG" },
        { name: "Bernardo Silva", position: "MDG" },
        { name: "Kovacic", position: "MDD" },
        { name: "Foden", position: "MOD" },
        { name: "Savinho", position: "MOG" },
        { name: "De Bruyne", position: "MOC" },
        { name: "Haaland", position: "AT" },
        { name: "Grealish J", position: "SUB0" },
        { name: "Lewis R", position: "SUB1" },
        { name: "McAtee", position: "SUB2" },
        { name: "Gundogan", position: "SUB3" },
        { name: "Stone", position: "SUB4" },
      ],
    },
    short: "La remontada parisienne",
    description:
      "Le PSG était 26e au classement, virtuellement éliminé à deux journées de la fin. Manchester City occupait la 24e place, dernière qualificative, avec un point d'avance sur le PSG. Les deux équipes avaient besoin d'une victoire pour maintenir leurs espoirs européens.",
  },
  {
    id: 3,
    homeTeam: { name: "FC Barcelone", formation: "4-3-3", color: "#a50044" },
    awayTeam: { name: "Real Madrid", formation: "4-4-2", color: "#FFFFFF" },
    competition: "La Liga",
    season: "2009-10",
    short: "La Manita",
    description:
      "Cette 'Manita' (5-0) est entrée dans l'histoire du football comme l'un des Clasicos les plus spectaculaires, marquant la supériorité du Barça de Guardiola et de Messi sur le Real Madrid de Mourinho. Le jeu collectif et la maestria technique des Catalans ont littéralement fait voler en éclats le système défensif madrilène, démontrant une différence de niveau qui a marqué les esprits du monde entier. Cette rencontre est devenue un moment emblématique qui symbolise l'âge d'or du football barcelonais sous la direction de Pep Guardiola.",
    date: "15e journée",
    score: "5-0",
    players: {
      home: [
        { name: "Pedro", position: "AT" },
        { name: "Messi", position: "ALG" },
        { name: "David Villa", position: "ALD" },
        { name: "Sergio Busquets", position: "MCG" },
        { name: "Andres Iniesta", position: "MCD" },
        { name: "Xavi", position: "MD" },
        { name: "Dani Alves", position: "DG" },
        { name: "E. Abidal", position: "DCG" },
        { name: "Piquet", position: "DCD" },
        { name: "Puyol", position: "DD" },
        { name: "Victor Valdes", position: "G" },
      ],
      away: [
        { name: "Cristiano Ronaldo", position: "ATG" },
        { name: "K. Benzema", position: "ATD" },
        { name: "Ozil", position: "MLG" },
        { name: "Xabi Alonso", position: "MDG" },
        { name: "S. Khedira", position: "MDD" },
        { name: "Di Maria", position: "MLD" },
        { name: "Sergio Ramos", position: "DG" },
        { name: "Ricardo Carvalho", position: "DCG" },
        { name: "Pepe", position: "DCD" },
        { name: "Marcelo", position: "DD" },
        { name: "Casillas", position: "G" },
      ],
    },
  },
  {
    id: 2,
    awayTeam: { name: "France", formation: "4-1-2-3", color: "#21304D" },
    homeTeam: { name: "Argentine", formation: "4-1-2-3", color: "#43A1D5" },
    competition: "Coupe du monde 2022",
    season: "",
    description:
      "Ce match est entré dans l'histoire comme l'une des finales les plus spectaculaires, se terminant sur un score de 3-3 après prolongation, avec un triplé de 2 joueurs légendaires. L'Argentine a finalement remporté le titre aux tirs au but (4-2), décrochant ainsi sa troisième étoile.",
    date: "Finale",
    score: "3-3",
    players: {
      home: [
        { name: "Alvarez", position: "AT" },
        { name: "Di Maria", position: "ALG" },
        { name: "Messi", position: "ALD" },
        { name: "Mac Allister", position: "MCG" },
        { name: "De Paul", position: "MCD" },
        { name: "Fernandez", position: "MD" },
        { name: "Tagliafico", position: "DG" },
        { name: "Romero", position: "DCD" },
        { name: "Otamendi", position: "DCG" },
        { name: "Molina", position: "DD" },
        { name: "Martinez", position: "G" },
        { name: "Acuna", position: "SUB0" },
        { name: "Montiel", position: "SUB1" },
        { name: "Paredes", position: "SUB2" },
        { name: "Martinez L.", position: "SUB3" },
        { name: "Pezzella", position: "SUB4" },
        { name: "Dybala", position: "SUB5" },
      ],
      away: [
        { name: "Mbappe", position: "ALG" },
        { name: "Giroud", position: "AT" },
        { name: "Dembele", position: "ALD" },
        { name: "Griezmann", position: "MCD" },
        { name: "Rabiot", position: "MCG" },
        { name: "Tchouameni", position: "MD" },
        { name: "Hernandez", position: "DG" },
        { name: "Upamecano", position: "DCD" },
        { name: "Varane", position: "DCG" },
        { name: "Kounde", position: "DD" },
        { name: "Lloris", position: "G" },
        { name: "Thuram", position: "SUB0" },
        { name: "Kolo Muani", position: "SUB1" },
        { name: "Coman", position: "SUB2" },
        { name: "Camavinga", position: "SUB3" },
        { name: "Fofana", position: "SUB4" },
        { name: "Konate", position: "SUB5" },
        { name: "Disasi", position: "SUB6" },
      ],
    },
  },
  {
    id: 4,
    homeTeam: { name: "FC Barcelone", formation: "4-3-3", color: "#a50044" },
    awayTeam: { name: "Real Madrid", formation: "4-3-3", color: "#FFFFFF" },
    competition: "La Liga",
    season: "2015-16",
    short: "Le fameux Calma, Calma",
    description:
      "le Real Madrid battait le FC Barcelone au Camp Nou grâce à un but de la légende portugaise en fin de match (2-1) ! 👀 Quelques semaines plus tard, les Merengue remportaient leur première Ligue des champions avec Zinédine Zidane sur le banc !",
    date: "15e journée",
    score: "1-2",
    players: {
      home: [
        { name: "Suarez", position: "AT" },
        { name: "Neymar Jr.", position: "ALG" },
        { name: "Messi", position: "ALD" },
        { name: "Andres Iniesta", position: "MCG" },
        { name: "Rakitic", position: "MCD" },
        { name: "Sergio Busquets", position: "MD" },
        { name: "Jordi Alba", position: "DG" },
        { name: "Mascherano", position: "DCG" },
        { name: "Pique", position: "DCD" },
        { name: "Dani Alves", position: "DD" },
        { name: "Victor Valdes", position: "G" },
      ],
      away: [
        { name: "Benzema", position: "AT" },
        { name: "Cristiano Ronaldo", position: "ALG" },
        { name: "Bale", position: "ALD" },
        { name: "Modric", position: "MCG" },
        { name: "Casemiro", position: "MD" },
        { name: "Kross", position: "MCD" },
        { name: "Marcelo", position: "DG" },
        { name: "Sergio Ramos", position: "DCG" },
        { name: "Pepe", position: "DCD" },
        { name: "Carvajal", position: "DD" },
        { name: "Navas", position: "G" },
      ],
    },
  },
]
